spring.datasource.url=${db-url}
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}
info.team-name=${team-name}
spring.jpa.hibernate.ddl-auto=update

management.endpoint.health.show-details=never

spring.config.import=aws-parameterstore:/cloud-architecture/prod/